services:
  api:
    container_name: fiber-api
    build: .
    ports: 
      - 9999:8888
    volumes:
      - ./:/build:delegated
    restart: always
    depends_on:
      - mysql
    networks:
      - fiber-bridge

  mysql:
    container_name: fiber-mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always # "no" | on-failure
    volumes:
      - fiber-data_mysql:/var/lib/mysql:delegated
    environment:
      - MYSQL_DATABASE=pos-v2
      - MYSQL_USER=fiber
      - MYSQL_PASSWORD=fiber
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - fiber-bridge

networks:
  fiber-bridge:

volumes:
  fiber-data_mysql:
