version: '3.8'

services:
  api:
    container_name: fiber-api
    build: .
    ports: 
      - 8888:8888
    volumes:
      - ./:/app
    restart: none # on-failure
    depends_on:
      - mysql
    networks:
      - fiber-bridge

  mysql:
    container_name: fiber-mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: none # on-failure
    volumes:
      - fiber-data_mysql:/var/lib/mysql:delegated
    environment:
      MYSQL_DATABASE: pos-v2
      MYSQL_ROOT_PASSWORD: root
    networks:
      - fiber-bridge

networks:
  fiber-bridge:
    driver: bridge

volumes:
  fiber-data_mysql:
    driver: local
