version: '3.8'

services:
  api:
    container_name: gofiber-api
    build: .
    ports: 
      - "8888:8888"
    restart: on-failure
    depends_on:
      - mysql
    networks:
      - bridge

  # la connexion ne fonctionne pas !
  mysql:
    container_name: gofiber-mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    volumes:
      - data_mysql:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - bridge

networks:
  bridge:
    driver: bridge

volumes:
  data_mysql:
    driver: local
